from __future__ import annotations

import copy
import hashlib
import hmac
import json
import sqlite3
import tempfile
import unittest
from contextlib import closing
from dataclasses import replace
from pathlib import Path

from instant_ai.blogger_ingest import (
    BloggerIngestError,
    BloggerIngestStore,
    BloggerManifestReceiver,
    BloggerManifestVerifier,
    DEFAULT_MANIFEST_PATH,
    HEADER_CONTENT_SHA256,
    HEADER_KEY_ID,
    HEADER_NODE_ID,
    HEADER_NONCE,
    HEADER_SIGNATURE,
    HEADER_TIMESTAMP,
    MANIFEST_SCHEMA_VERSION,
    MAX_MANIFEST_BYTES,
    ManifestAuthentication,
    V1_MEDIA_MIME_TYPES,
    canonical_request_bytes,
    decode_manifest,
    sign_manifest,
)


NODE_ID = "beijing-collector-1"
KEY_ID = "hmac-2026-01"
NOW = 1_800_000_100

# Fixed cross-implementation vector generated by Beijing's authoritative
# mx_agent.transfer_contract at 2026-08-30. Keep the 32-byte secret, body and
# headers literal: rebuilding any of them with receiver helpers would make this
# compatibility test circular.
GOLDEN_SECRET = bytes.fromhex(
    "000102030405060708090a0b0c0d0e0f"
    "101112131415161718191a1b1c1d1e1f"
)
GOLDEN_BODY = (
    b'{"captured_at":"2026-08-30T10:05:00+08:00","collector":{"key_id":"hmac-2026-01",'
    b'"node_id":"beijing-collector-1","source_sequence":41,"version":"0.1.0"},'
    b'"comment_snapshot":{"bundle":{"bundle_id":"92fe97f529f846873061a632e213bdc4a9badb701631a871fdc625bbf56a080b",'
    b'"content_encoding":"gzip","format":"blogger-comments/v1+ndjson","item_count":2,'
    b'"sha256":"92fe97f529f846873061a632e213bdc4a9badb701631a871fdc625bbf56a080b",'
    b'"size_bytes":413,"uncompressed_sha256":"c9e908cac5d077b62ba4b81e8e33ff01352f0c6b28fc21989f8407a7806174e6",'
    b'"uncompressed_size_bytes":1090},"captured_at":"2026-08-30T10:05:00+08:00",'
    b'"captured_count":2,"complete":false,"expected_total":3,"missing_replies":1,'
    b'"orphan_replies":0,"reply_groups":1,"reply_groups_incomplete":1,'
    b'"rules_version":"comment-rules/v1","snapshot_id":"snapshot-1","top_level_count":1},'
    b'"creator":{"creator_id":"7de6f4d1-3bf6-4c8b-b2e4-3d8b285dcb5e",'
    b'"display_name":"golden-creator","platform":"douyin",'
    b'"platform_user_id":"MS4wLjABAAAA-example"},"media":[{"filename":"sample.mp4",'
    b'"media_id":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",'
    b'"mime_type":"video/mp4","ordinal":0,"role":"video",'
    b'"sha256":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",'
    b'"size_bytes":2048},{"filename":"cover.jpg",'
    b'"media_id":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",'
    b'"mime_type":"image/jpeg","ordinal":1,"role":"cover",'
    b'"sha256":"bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",'
    b'"size_bytes":1024}],"revision_sha256":"2c9e3a327d1596279cf7c94feb9145f56701b0833c0b009666024d0e478b80b1",'
    b'"schema_version":"blogger-transfer/v1",'
    b'"transfer_id":"289b8956116fc2edc8494c95478cc909ad27c1baea000e1b030b02ac9ec1caa3",'
    b'"work":{"cover_url":"","description":"public description","platform":"douyin",'
    b'"published_at":"2026-08-30T10:00:00+08:00","revision":7,'
    b'"source_url":"https://www.douyin.com/video/7654321098765432100",'
    b'"source_work_id":"7654321098765432100","title":"golden-work","work_type":"video"}}'
)
GOLDEN_HEADERS = {
    HEADER_NODE_ID: NODE_ID,
    HEADER_KEY_ID: KEY_ID,
    HEADER_TIMESTAMP: "1800000000",
    HEADER_NONCE: "0123456789abcdef0123456789abcdef",
    HEADER_CONTENT_SHA256: "ecc685e0f247b43023754e49fbe499785808668303a2d71699087cd94fd2e889",
    HEADER_SIGNATURE: "71d2c5343ca32c2aa4c49591edf181fc9317578c22a51b2c46bf31b8b4bc7980",
}
GOLDEN_REVISION_SHA256 = "2c9e3a327d1596279cf7c94feb9145f56701b0833c0b009666024d0e478b80b1"
GOLDEN_TRANSFER_ID = "289b8956116fc2edc8494c95478cc909ad27c1baea000e1b030b02ac9ec1caa3"


def _canonical(value: dict) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _rehash(value: dict) -> dict:
    manifest = copy.deepcopy(value)
    manifest.pop("revision_sha256", None)
    manifest.pop("transfer_id", None)
    revision_sha256 = hashlib.sha256(_canonical(manifest)).hexdigest()
    identity = "\n".join(
        (
            manifest["collector"]["node_id"],
            manifest["creator"]["creator_id"],
            manifest["work"]["platform"],
            manifest["work"]["source_work_id"],
            str(manifest["work"]["revision"]),
            revision_sha256,
        )
    ).encode("utf-8")
    manifest["revision_sha256"] = revision_sha256
    manifest["transfer_id"] = hashlib.sha256(identity).hexdigest()
    return manifest


def _manifest(*, revision: int = 7, sequence: int = 41, title: str = "golden-work") -> dict:
    value = json.loads(GOLDEN_BODY)
    value["collector"]["source_sequence"] = sequence
    value["work"]["revision"] = revision
    value["work"]["title"] = title
    return _rehash(value)


class BloggerManifestIngestTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name) / "blogger-agent"
        self.receiver = BloggerManifestReceiver(
            root=self.root,
            secrets={(NODE_ID, KEY_ID): GOLDEN_SECRET},
            clock=lambda: NOW,
        )
        self.nonce_counter = 100

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def _authentication(
        self,
        body: bytes,
        *,
        node_id: str = NODE_ID,
        key_id: str = KEY_ID,
        timestamp: int = 1_800_000_000,
        nonce: str | None = None,
        secret: bytes = GOLDEN_SECRET,
    ) -> ManifestAuthentication:
        self.nonce_counter += 1
        return sign_manifest(
            secret,
            body,
            node_id=node_id,
            key_id=key_id,
            timestamp=timestamp,
            nonce=nonce or f"{self.nonce_counter:032x}",
        )

    def _receive_manifest(self, manifest: dict, **authentication_overrides):
        body = _canonical(manifest)
        return self.receiver.receive(body, self._authentication(body, **authentication_overrides))

    def _assert_error(self, code: str, callback) -> BloggerIngestError:
        with self.assertRaises(BloggerIngestError) as captured:
            callback()
        self.assertEqual(captured.exception.code, code)
        return captured.exception

    def test_beijing_golden_body_and_headers_are_accepted_verbatim(self) -> None:
        self.assertEqual(len(GOLDEN_SECRET), 32)
        self.assertEqual(hashlib.sha256(GOLDEN_BODY).hexdigest(), GOLDEN_HEADERS[HEADER_CONTENT_SHA256])
        signed = canonical_request_bytes(
            method="POST",
            path=DEFAULT_MANIFEST_PATH,
            node_id=NODE_ID,
            key_id=KEY_ID,
            timestamp=GOLDEN_HEADERS[HEADER_TIMESTAMP],
            nonce=GOLDEN_HEADERS[HEADER_NONCE],
            content_sha256=GOLDEN_HEADERS[HEADER_CONTENT_SHA256],
        )
        self.assertEqual(
            signed,
            (
                "POST\n/internal/v1/transfers\nbeijing-collector-1\n"
                "hmac-2026-01\n1800000000\n"
                "0123456789abcdef0123456789abcdef\n"
                "ecc685e0f247b43023754e49fbe499785808668303a2d71699087cd94fd2e889"
            ).encode("utf-8"),
        )
        self.assertEqual(
            hmac.new(GOLDEN_SECRET, signed, hashlib.sha256).hexdigest(),
            GOLDEN_HEADERS[HEADER_SIGNATURE],
        )

        receipt = self.receiver.receive(
            GOLDEN_BODY,
            ManifestAuthentication.from_headers(GOLDEN_HEADERS),
        )

        self.assertEqual(receipt.status, "accepted")
        self.assertEqual(receipt.transfer_id, GOLDEN_TRANSFER_ID)
        self.assertEqual(receipt.revision_sha256, GOLDEN_REVISION_SHA256)
        self.assertEqual(
            receipt.as_dict(),
            {
                "status": "accepted",
                "transfer_id": GOLDEN_TRANSFER_ID,
                "receipt_id": GOLDEN_TRANSFER_ID,
                "revision_sha256": GOLDEN_REVISION_SHA256,
                "work_revision": 7,
                "current_revision": 7,
                "missing_artifacts": [
                    {"artifact_id": "a" * 64, "artifact_kind": "media"},
                    {"artifact_id": "b" * 64, "artifact_kind": "media"},
                    {
                        "artifact_id": "92fe97f529f846873061a632e213bdc4a9badb701631a871fdc625bbf56a080b",
                        "artifact_kind": "comment_bundle",
                    },
                ],
            },
        )
        stored = self.receiver.store.get_current(
            work_platform="douyin",
            creator_id="7de6f4d1-3bf6-4c8b-b2e4-3d8b285dcb5e",
            source_work_id="7654321098765432100",
        )
        self.assertEqual(stored["manifest"]["media"][0]["role"], "video")
        self.assertEqual(stored["manifest"]["comment_snapshot"]["captured_count"], 2)

    def test_manifest_limit_allows_exactly_one_mib_and_rejects_one_byte_more(self) -> None:
        exact = GOLDEN_BODY + (b" " * (MAX_MANIFEST_BYTES - len(GOLDEN_BODY)))
        self.assertEqual(len(exact), MAX_MANIFEST_BYTES)
        receipt = self.receiver.receive(exact, self._authentication(exact))
        self.assertEqual(receipt.status, "accepted")

        oversized = exact + b" "
        error = self._assert_error(
            "manifest_too_large",
            lambda: self.receiver.receive(oversized, self._authentication(oversized)),
        )
        self.assertNotIn(GOLDEN_SECRET.hex(), str(error))

    def test_signature_binds_all_seven_lines_and_rejects_bad_authentication(self) -> None:
        authentication = ManifestAuthentication.from_headers(GOLDEN_HEADERS)
        tampered_body = GOLDEN_BODY.replace(b"golden-work", b"golden-WORK")
        self._assert_error(
            "content_digest_mismatch",
            lambda: self.receiver.receive(tampered_body, authentication),
        )
        wrong_verifier = BloggerManifestVerifier({(NODE_ID, KEY_ID): b"x" * 32})
        self._assert_error(
            "invalid_signature",
            lambda: wrong_verifier.verify(GOLDEN_BODY, authentication, now=NOW),
        )
        for changed in (
            {"method": "PUT"},
            {"path": "/internal/v1/other"},
        ):
            with self.subTest(changed=changed):
                self._assert_error(
                    "invalid_signature",
                    lambda changed=changed: self.receiver.verifier.verify(
                        GOLDEN_BODY,
                        authentication,
                        now=NOW,
                        **changed,
                    ),
                )
        missing = dict(GOLDEN_HEADERS)
        missing.pop(HEADER_SIGNATURE)
        self._assert_error(
            "invalid_authentication",
            lambda: ManifestAuthentication.from_headers(missing),
        )

    def test_clock_window_is_inclusive_and_rejects_past_or_future_301_seconds(self) -> None:
        verifier = self.receiver.verifier
        for timestamp in (NOW - 300, NOW + 300):
            authentication = self._authentication(GOLDEN_BODY, timestamp=timestamp)
            self.assertEqual(
                verifier.verify(GOLDEN_BODY, authentication, now=NOW),
                hashlib.sha256(GOLDEN_BODY).hexdigest(),
            )
        for timestamp in (NOW - 301, NOW + 301):
            authentication = self._authentication(GOLDEN_BODY, timestamp=timestamp)
            self._assert_error(
                "expired_request",
                lambda authentication=authentication: verifier.verify(
                    GOLDEN_BODY,
                    authentication,
                    now=NOW,
                ),
            )

    def test_header_node_and_key_must_match_the_manifest(self) -> None:
        secrets = {
            (NODE_ID, KEY_ID): GOLDEN_SECRET,
            ("beijing-collector-2", KEY_ID): GOLDEN_SECRET,
            (NODE_ID, "hmac-2026-02"): GOLDEN_SECRET,
        }
        receiver = BloggerManifestReceiver(root=self.root, secrets=secrets, clock=lambda: NOW)
        for node_id, key_id in (
            ("beijing-collector-2", KEY_ID),
            (NODE_ID, "hmac-2026-02"),
        ):
            authentication = self._authentication(
                GOLDEN_BODY,
                node_id=node_id,
                key_id=key_id,
            )
            with self.subTest(node_id=node_id, key_id=key_id):
                self._assert_error(
                    "collector_auth_mismatch",
                    lambda authentication=authentication: receiver.receive(
                        GOLDEN_BODY,
                        authentication,
                    ),
                )

    def test_nonce_is_normalized_and_persists_across_receiver_restarts(self) -> None:
        nonce = "fedcba9876543210fedcba9876543210"
        spaced = self._authentication(GOLDEN_BODY, nonce=f"  {nonce}  ")
        self.assertEqual(self.receiver.receive(GOLDEN_BODY, spaced).status, "accepted")

        restarted = BloggerManifestReceiver(
            root=self.root,
            secrets={(NODE_ID, KEY_ID): GOLDEN_SECRET},
            clock=lambda: NOW,
        )
        replay = self._authentication(GOLDEN_BODY, nonce=nonce)
        self._assert_error(
            "replayed_nonce",
            lambda: restarted.receive(GOLDEN_BODY, replay),
        )

    def test_fresh_nonce_makes_same_transfer_an_idempotent_duplicate(self) -> None:
        first = self.receiver.receive(
            GOLDEN_BODY,
            ManifestAuthentication.from_headers(GOLDEN_HEADERS),
        )
        second = self.receiver.receive(GOLDEN_BODY, self._authentication(GOLDEN_BODY))
        self.assertEqual(first.status, "accepted")
        self.assertEqual(second.status, "duplicate")
        self.assertEqual(second.as_dict()["missing_artifacts"], first.as_dict()["missing_artifacts"])
        with closing(sqlite3.connect(self.receiver.store.database_path)) as connection:
            self.assertEqual(connection.execute("SELECT COUNT(*) FROM transfers").fetchone()[0], 1)

    def test_higher_revision_supersedes_and_lower_revision_gets_stale_ack(self) -> None:
        revision_8 = _manifest(revision=8, sequence=42, title="revision-8")
        revision_7 = _manifest(revision=7, sequence=999, title="older-from-high-sequence")
        newest = self._receive_manifest(revision_8)
        stale = self._receive_manifest(revision_7)
        self.assertEqual(newest.status, "accepted")
        self.assertEqual(stale.status, "stale")
        self.assertEqual(stale.current_revision, 8)
        self.assertEqual(stale.as_dict()["missing_artifacts"], [])
        current = self.receiver.store.get_current(
            work_platform="douyin",
            creator_id=revision_8["creator"]["creator_id"],
            source_work_id=revision_8["work"]["source_work_id"],
        )
        self.assertEqual(current["source_revision"], 8)

    def test_retry_of_previously_accepted_revision_becomes_stale_after_supersession(self) -> None:
        old = _manifest(revision=7, sequence=41, title="revision-7")
        new = _manifest(revision=8, sequence=42, title="revision-8")
        old_receipt = self._receive_manifest(old)
        self.assertEqual(self._receive_manifest(new).status, "accepted")
        replay = self._receive_manifest(old)
        self.assertEqual(replay.status, "stale")
        self.assertEqual(replay.transfer_id, old_receipt.transfer_id)
        self.assertEqual(replay.current_revision, 8)
        self.assertEqual(replay.as_dict()["missing_artifacts"], [])
        self.assertEqual(self.receiver.store.get_transfer(old_receipt.transfer_id)["state"], "superseded")

    def test_same_work_revision_with_different_content_is_a_conflict(self) -> None:
        original = _manifest(revision=7, title="first-body")
        conflicting = _manifest(revision=7, sequence=42, title="different-body")
        accepted = self._receive_manifest(original)
        self._assert_error(
            "revision_conflict",
            lambda: self._receive_manifest(conflicting),
        )
        current = self.receiver.store.get_current(
            work_platform="douyin",
            creator_id=original["creator"]["creator_id"],
            source_work_id=original["work"]["source_work_id"],
        )
        self.assertEqual(current["transfer_id"], accepted.transfer_id)
        self.assertEqual(current["manifest"]["work"]["title"], "first-body")

    def test_transfer_id_cannot_alias_a_different_canonical_manifest(self) -> None:
        validated = decode_manifest(GOLDEN_BODY)
        self.receiver.store.accept_manifest(
            validated,
            request_sha256=hashlib.sha256(GOLDEN_BODY).hexdigest(),
            received_at=NOW,
        )
        forged = replace(validated, canonical_json=validated.canonical_json + " ")
        self._assert_error(
            "transfer_conflict",
            lambda: self.receiver.store.accept_manifest(
                forged,
                request_sha256=hashlib.sha256(GOLDEN_BODY).hexdigest(),
                received_at=NOW,
            ),
        )

    def test_revision_sha256_and_transfer_id_are_recomputed_not_trusted(self) -> None:
        for field, code in (
            ("revision_sha256", "revision_digest_mismatch"),
            ("transfer_id", "transfer_id_mismatch"),
        ):
            manifest = json.loads(GOLDEN_BODY)
            manifest[field] = "0" * 64
            body = _canonical(manifest)
            with self.subTest(field=field):
                self._assert_error(
                    code,
                    lambda body=body: self.receiver.receive(body, self._authentication(body)),
                )

    def test_creator_uuid_and_positive_integer_work_revision_are_strict(self) -> None:
        invalid_values = (
            (lambda value: value["creator"].__setitem__("creator_id", "not-a-uuid"), "invalid_manifest"),
            (lambda value: value["work"].__setitem__("revision", 0), "invalid_manifest"),
            (lambda value: value["work"].__setitem__("revision", True), "invalid_manifest"),
            (lambda value: value["work"].__setitem__("revision", "7"), "invalid_manifest"),
        )
        for mutate, code in invalid_values:
            manifest = json.loads(GOLDEN_BODY)
            mutate(manifest)
            body = _canonical(_rehash(manifest))
            with self.subTest(body=body[:100]):
                self._assert_error(code, lambda body=body: decode_manifest(body))

    def test_media_array_is_strict_bounded_and_path_safe(self) -> None:
        cases = []
        not_array = json.loads(GOLDEN_BODY)
        not_array["media"] = {}
        cases.append(not_array)
        bad_role = json.loads(GOLDEN_BODY)
        bad_role["media"][0]["role"] = "executable"
        cases.append(bad_role)
        duplicate = json.loads(GOLDEN_BODY)
        duplicate["media"][1]["media_id"] = duplicate["media"][0]["media_id"]
        cases.append(duplicate)
        unsafe_path = json.loads(GOLDEN_BODY)
        unsafe_path["media"][0]["filename"] = "../secret.mp4"
        cases.append(unsafe_path)
        too_many = json.loads(GOLDEN_BODY)
        too_many["media"] = [
            {
                "media_id": hashlib.sha256(str(index).encode()).hexdigest(),
                "role": "image",
                "filename": f"{index}.jpg",
                "mime_type": "image/jpeg",
                "size_bytes": 1,
                "sha256": hashlib.sha256(f"body-{index}".encode()).hexdigest(),
                "ordinal": index,
            }
            for index in range(101)
        ]
        cases.append(too_many)
        for manifest in cases:
            body = _canonical(_rehash(manifest))
            with self.subTest(media=manifest["media"] if isinstance(manifest["media"], dict) else len(manifest["media"])):
                self._assert_error("invalid_manifest", lambda body=body: decode_manifest(body))

    def test_v1_role_mime_matrix_is_literal_and_rejected_during_manifest_ingest(self) -> None:
        self.assertEqual(
            V1_MEDIA_MIME_TYPES,
            {
                "video": frozenset({"video/mp4"}),
                "image": frozenset({"image/jpeg", "image/png", "image/webp"}),
                "cover": frozenset({"image/jpeg", "image/png", "image/webp"}),
            },
        )
        unsupported = (
            ("audio", "audio/mp4"),
            ("video", "application/mp4"),
            ("video", "application/octet-stream"),
            ("video", "image/jpeg"),
            ("image", "video/mp4"),
            ("cover", "image/gif"),
        )
        for role, mime_type in unsupported:
            manifest = json.loads(GOLDEN_BODY)
            manifest["media"][0]["role"] = role
            manifest["media"][0]["mime_type"] = mime_type
            body = _canonical(_rehash(manifest))
            with self.subTest(role=role, mime_type=mime_type):
                self._assert_error("invalid_manifest", lambda body=body: decode_manifest(body))

    def test_comment_snapshot_requires_descriptor_counts_format_and_exact_fields(self) -> None:
        cases = []
        mismatch = json.loads(GOLDEN_BODY)
        mismatch["comment_snapshot"]["captured_count"] = 3
        cases.append(mismatch)
        bad_format = json.loads(GOLDEN_BODY)
        bad_format["comment_snapshot"]["bundle"]["format"] = "application/json"
        cases.append(bad_format)
        bad_encoding = json.loads(GOLDEN_BODY)
        bad_encoding["comment_snapshot"]["bundle"]["content_encoding"] = "identity"
        cases.append(bad_encoding)
        missing_rule = json.loads(GOLDEN_BODY)
        missing_rule["comment_snapshot"].pop("rules_version")
        cases.append(missing_rule)
        wrong_boolean = json.loads(GOLDEN_BODY)
        wrong_boolean["comment_snapshot"]["complete"] = "false"
        cases.append(wrong_boolean)
        for manifest in cases:
            body = _canonical(_rehash(manifest))
            self._assert_error("invalid_manifest", lambda body=body: decode_manifest(body))

    def test_unknown_duplicate_nonfinite_and_non_utf8_json_are_rejected(self) -> None:
        extra = json.loads(GOLDEN_BODY)
        extra["local_path"] = "C:/private/video.mp4"
        payloads = (
            _canonical(_rehash(extra)),
            b'{"schema_version":"blogger-transfer/v1","schema_version":"blogger-transfer/v1"}',
            b'{"schema_version":NaN}',
            b"\xff\xfe",
        )
        for body in payloads:
            with self.subTest(body=body[:80]):
                self._assert_error("invalid_manifest", lambda body=body: decode_manifest(body))
        unknown_schema = json.loads(GOLDEN_BODY)
        unknown_schema["schema_version"] = "blogger-transfer/v2"
        body = _canonical(_rehash(unknown_schema))
        self._assert_error("unsupported_schema", lambda: decode_manifest(body))

    def test_store_is_git_external_in_shape_and_never_persists_the_secret(self) -> None:
        self.receiver.receive(
            GOLDEN_BODY,
            ManifestAuthentication.from_headers(GOLDEN_HEADERS),
        )
        self.assertEqual(self.receiver.store.database_path, self.root / "database" / "blogger_ingest.db")
        self.assertEqual({path.name for path in self.root.iterdir()}, {"database"})
        self.assertFalse((self.root / "media").exists())
        database_bytes = self.receiver.store.database_path.read_bytes()
        self.assertNotIn(GOLDEN_SECRET, database_bytes)
        with closing(sqlite3.connect(self.receiver.store.database_path)) as connection:
            tables = {
                row[0]
                for row in connection.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"
                )
            }
        self.assertEqual(
            tables,
            {"artifacts", "processing_queue", "replay_nonces", "schema_meta", "transfers"},
        )
        self.assertNotEqual(self.receiver.store.database_path.name, "instant_ai.db")
        self.assertNotIn("model-mr", str(self.receiver.store.database_path))

    def test_version_two_ledger_is_migrated_and_artifacts_are_backfilled(self) -> None:
        migrated_root = Path(self.temporary.name) / "migrated-blogger-agent"
        database_root = migrated_root / "database"
        database_root.mkdir(parents=True)
        database_path = database_root / "blogger_ingest.db"
        validated = decode_manifest(GOLDEN_BODY)
        with closing(sqlite3.connect(database_path)) as connection:
            connection.executescript(
                """
                CREATE TABLE schema_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
                INSERT INTO schema_meta(key, value) VALUES('schema_version', '2');
                CREATE TABLE replay_nonces (
                    node_id TEXT NOT NULL, nonce TEXT NOT NULL, key_id TEXT NOT NULL,
                    request_timestamp INTEGER NOT NULL, request_sha256 TEXT NOT NULL,
                    seen_at INTEGER NOT NULL, expires_at INTEGER NOT NULL,
                    PRIMARY KEY(node_id, nonce)
                );
                CREATE TABLE transfers (
                    transfer_id TEXT PRIMARY KEY, schema_version TEXT NOT NULL,
                    collector_node_id TEXT NOT NULL, collector_key_id TEXT NOT NULL,
                    collector_source_sequence INTEGER NOT NULL, request_sha256 TEXT NOT NULL,
                    revision_sha256 TEXT NOT NULL, creator_id TEXT NOT NULL,
                    creator_display_name TEXT NOT NULL, creator_platform TEXT NOT NULL,
                    platform_user_id TEXT NOT NULL, work_platform TEXT NOT NULL,
                    source_work_id TEXT NOT NULL, source_revision INTEGER NOT NULL,
                    state TEXT NOT NULL, is_current INTEGER NOT NULL,
                    received_at INTEGER NOT NULL, manifest_json TEXT NOT NULL
                );
                """
            )
            connection.execute(
                """
                INSERT INTO transfers VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    validated.transfer_id,
                    MANIFEST_SCHEMA_VERSION,
                    validated.collector_node_id,
                    validated.collector_key_id,
                    validated.collector_source_sequence,
                    hashlib.sha256(GOLDEN_BODY).hexdigest(),
                    validated.revision_sha256,
                    validated.creator_id,
                    validated.creator_display_name,
                    validated.creator_platform,
                    validated.platform_user_id,
                    validated.work_platform,
                    validated.source_work_id,
                    validated.source_revision,
                    "accepted",
                    1,
                    NOW,
                    validated.canonical_json,
                ),
            )
            connection.commit()

        store = BloggerIngestStore(migrated_root)
        transfer = store.get_transfer(validated.transfer_id)
        self.assertEqual(len(transfer["opaque_work_key"]), 64)
        self.assertEqual(transfer["transport_status"], "accepted")
        self.assertEqual(len(transfer["artifacts"]), 3)
        self.assertTrue(all(item["state"] == "pending" for item in transfer["artifacts"]))
        with closing(sqlite3.connect(database_path)) as connection:
            version = connection.execute(
                "SELECT value FROM schema_meta WHERE key='schema_version'"
            ).fetchone()[0]
        self.assertEqual(version, "3")

    def test_header_names_are_case_insensitive_and_values_are_trimmed(self) -> None:
        headers = {name.lower(): f"  {value}  " for name, value in GOLDEN_HEADERS.items()}
        authentication = ManifestAuthentication.from_headers(headers)
        self.assertEqual(authentication.node_id, NODE_ID)
        self.assertEqual(authentication.nonce, GOLDEN_HEADERS[HEADER_NONCE])
        self.assertEqual(self.receiver.receive(GOLDEN_BODY, authentication).status, "accepted")


if __name__ == "__main__":
    unittest.main()
